(defun mahori:default-mode-hook ()
  (display-line-numbers-mode 1)
  )

(defun mahori:dns-mode-hook ()
  (setq indent-tabs-mode t)
  (setq tab-width 8)
  (mahori:default-mode-hook)
  )

(add-hook 'conf-unix-mode-hook 'mahori:default-mode-hook)
(add-hook 'default-generic-mode-hook 'mahori:default-mode-hook)
(add-hook 'dns-mode-hook 'mahori:dns-mode-hook)
(add-hook 'etc-passwd-generic-mode-hook 'mahori:default-mode-hook)
(add-hook 'etc-sudoers-generic-mode-hook 'mahori:default-mode-hook)
(add-hook 'hosts-generic-mode-hook 'mahori:default-mode-hook)
