(defun mahori:ruby-mode-hook ()
  (setq ruby-deep-indent-paren-style nil)
  (auto-revert-mode 1)
  (company-mode 1)
  (display-line-numbers-mode 1)
  (hl-line-mode 1)
  (show-paren-mode 1)
  (yas-minor-mode 1)
  )

(add-hook 'ruby-mode-hook 'mahori:ruby-mode-hook)
