(defun mahori:sh-mode-hook ()
  (auto-revert-mode 1)
  (company-mode 1)
  (display-line-numbers-mode 1)
  (git-gutter-mode 1)
  (hl-line-mode 1)
  (show-paren-mode 1)
  (yas-minor-mode 1)
  )

(add-hook 'sh-mode-hook 'mahori:sh-mode-hook)
